version: '3.8'
services:
  backend:
    build: ./backend
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: wheat_innovation
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: wheat_innovation
      MB_DB_PORT: 5432
      MB_DB_USER: admin
      MB_DB_PASS: admin
      MB_DB_HOST: postgres
volumes:
  pgdata:
